# Generated by Django 5.2.6 on 2025-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
