"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
import urllib.parse
from pathlib import Path
# only dev env
from corsheaders.defaults import default_headers


env = environ.Env(
  DEBUG=(bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
ENV = env("DJANGO_ENV", default="dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

if ENV == "development":
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.0.101"] 


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    # for markdown
    'markdownx',
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used  # optional, for special form elements

    

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize', 
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #for cms tags
    'taggit',
    'taggit_autosuggest',

    # custom apps
    'accounts',
    'users',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Social providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.twitter',
    # 'allauth.socialaccount.providers.twitter_oauth2',
    # 'allauth.socialaccount.providers.telegram',

    # for automatic tasks
    'django_celery_beat',

    # api and realtime communication
    'rest_framework',
    'channels',
    #social oauth
    # 'social_django',

    # my apps
    
    'projects',
    'chats',
    'blogs'
    
]

ASGI_APPLICATION = 'portfolio.asgi.application'


REDIS_WEBSOCKET_URL = env("REDIS_WEBSOCKET_URL", default="redis://127.0.0.1:6379/0")
REDIS_CACHE_URL = env("REDIS_CACHE_URL", default="redis://127.0.0.1:6379/1")


# Redis channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_WEBSOCKET_URL],
        },
    },
}


CACHES={
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
                
        }
    }
}

    

CELERY_BROKER_URL=os.getenv("REDIS_CELERY_BROKER_URL", default="redis://127.0.0.1:6379/2")
CELERY_RESULT_BACKEND=os.getenv("REDIS_CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/3")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = 'UTC'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.AdminObscurityMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    # profile completion middleware
    'accounts.middleware.ProfileCompletionMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    # #social oauth
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
]


# Provider specific settings




# It's required for chat app in development
if ENV == "dev":
    INSTALLED_APPS += ['corsheaders']

    MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
        *MIDDLEWARE,
    ]

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # React dev server
    ]

    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
    ]

    CORS_ALLOW_HEADERS = list(default_headers) + [
        "Idempotency-Key",
    ]


    CORS_ALLOW_CREDENTIALS = True

    SESSION_COOKIE_SAMESITE = "Lax"  # or "None" with HTTPS
    SESSION_COOKIE_SECURE = False    # In dev only


SESSION_ENGINE = 'django.contrib.sessions.backends.db' 

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                # `allauth` needs this from django
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'

UNFOLD = {
    "SITE_TITLE": "Saidbek.dev",
    "SITE_HEADER": "Dashboard",
    "SHOW_HISTORY": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
   "COLORS": {
        "primary": {
            "50":  "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",  # main accent (blue-500)
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
        },
        "gray": {
            "50":  "#f9fafb",
            "100": "#f3f4f6",
            "200": "#e5e7eb",
            "300": "#d1d5db",
            "400": "#9ca3af",
            "500": "#6b7280",  # neutral gray
            "600": "#4b5563",
            "700": "#374151",
            "800": "#1f2937",
            "900": "#111827",
        },
        "success": {
            "500": "#22c55e"
        },
        "warning": {
            "500": "#eab308"
        },
        "danger": {
            "500": "#ef4444"
        },
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db()
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



AUTHENTICATION_BACKENDS = [
    # 'users.backends.EmailBackend',  # user login via email
    # 'social_core.backends.google.GoogleOAuth2',   # Google OAuth
    'django.contrib.auth.backends.ModelBackend',  # admin login via username
    'allauth.account.auth_backends.AuthenticationBackend',  # For allauth
    
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# for production 
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'youremail@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'

SITE_ID = 1
AUTH_USER_MODEL = 'users.CustomUser'
# it should be revised after customization of templates
ACCOUNT_ADAPTER = 'accounts.adapters.AdvancedAccountAdapter'
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = False
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Confirm immediately when user clicks
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True  # logout directly when visiting logout URL

ACCOUNT_SIGNUP_FIELDS=['email*', 'password1*']
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_LOGOUT_REDIRECT_URL = 'home' # where to go after logout

ACCOUNT_EMAIL_EDITABLE = False # this prohibits email update for users

# Redirects
LOGIN_REDIRECT_URL = 'home' # where to go after login
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True # logs out other devices except current
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False # logs out other devices except current

ACCOUNT_PASSWORD_CHANGE_REDIRECT_URL = '/users/profile/' 
ACCOUNT_PASSWORD_SET_REDIRECT_URL = '/users/profile/'

# Social OAuth Configuration 
SOCIALACCOUNT_LOGIN_ON_GET = True  # This removes the intermediate page
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True   # Automatically create accounts
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        # "APP": {
        #     "client_id": env("GOOGLE_CLIENT_ID"),
        #     "secret": env("GOOGLE_CLIENT_SECRET"),
        #     "key": ""
        # }
    },
    "github": {
        "SCOPE": ["user", "email"],
        # "APP": {
        #     "client_id": env("GITHUB_CLIENT_ID"),
        #     "secret": env("GITHUB_CLIENT_SECRET"),
        #     "key": ""
        # }
    },
    # "twitter_oauth2": {
    #     # "APP": {
    #     #     "client_id": env("TWITTER_CLIENT_ID"),
    #     #     "secret": env("TWITTER_CLIENT_SECRET"),
    #     #     "key": ""
    #     # }
    # },
    # "telegram": {
    #     # "APP": {
    #     #     "client_id": env("TELEGRAM_BOT_TOKEN"),
    #     #     "secret": "",
    #     #     "key": ""
    #     # }
    # }
}


# SOCIAL_AUTH_PIPELINE = (
#     'social_core.pipeline.social_auth.social_details',
#     'social_core.pipeline.social_auth.social_uid',
#     'social_core.pipeline.social_auth.auth_allowed',
#     'social_core.pipeline.social_auth.social_user',
#     'social_core.pipeline.user.get_username',
#     'social_core.pipeline.user.create_user',

#     'users.pipeline.save_user_details',  # Custom step
#     'social_core.pipeline.social_auth.associate_user',
#     'social_core.pipeline.social_auth.load_extra_data',
#     'social_core.pipeline.user.user_details',
# )


# GOOGLE AUTH
# Redirect URLs
# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env('GOOGLE_CLIENT_ID')
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env('GOOGLE_CLIENT_SECRET')

# SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']
# SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name']
# SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True
USE_I18N = True
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tashkent'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MARKDOWNX_MEDIA_PATH = 'markdownx/'
MARKDOWNX_UPLOAD_CONTENT_TYPES = ['image/jpeg', 'image/png']
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.fenced_code',
    'markdown.extensions.codehilite',  # enables pygments
]

MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {
    "codehilite": {
        "guess_lang": False,
        "use_pygments": True,
        "noclasses": False,  # use CSS classes (so we can style with Tailwind)
        # "wrapcode": True,    # force <pre><code> wrapper
    }
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
